backend:
  name  : github
  repo  : gaou-piou/Penrose
  branch: master
media_folder: "images/uploads"
collections:
  -
    label : "Settings"
    name  : "settings"
    delete: false
    extension: "json"
    editor: 
      preview: false
    files:
      -
        label : "Site Settings"
        name  : "general"
        file  : "site/_data/settings.json"
        fields: 
          - {label: "Global site title", name: "site_title", widget: "string"}
          - {label: "Global site description", name: "site_description", widget: "string"}
  -
    label: "English site"
    name: "en_site"
    delete: false
    extension: "json"
    editor: 
      preview: false
    files:
      -
        label: "Penrose page"
        name: "penrose"
        file: "site/_content/_en/penrose.json"
        fields:
          -
            label: "Navigation button text"
            name: "nav_content"
            widget: "string"
          -
            label: "Header settings"
            name: "header_content"
            widget: "object"
            fields:
              - {label: "Intro text", name: "intro", widget: "markdown"}
              - {label: "Button text", name: "btn", widget: "string"}
          -
            label: "Page settings"
            name: "page_content"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Content", name: "content", widget: "markdown"}
          -
            label: "Services"
            name: 'services'
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Icon", name: "icon", widget: "image"}
              - {label: "Subtitle", name: "subtitle", widget: "text", required: false}
              - {label: "Excerpt", name: "excerpt", widget: "text"}
              - {label: "Body", name: "body", widget: "markdown"}
      -
        label: "GDPR page"
        name: "gdbr"
        file: "site/_content/_en/gdbr.json"
        fields:
          -
            label: "Navigation button text"
            name: "nav_content"
            widget: "string"
          -
            label: "Page settings"
            name: "page_content"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
          -
            label: "Sections"
            name: 'sections'
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Icon", name: "icon", widget: "image"}
              - {label: "Excerpt", name: "excerpt", widget: "text"}