
backend:
  name: github
  repo: gaou-piou/Penrose
media_folder: "images/uploads"
display_url: https://www.penrose.gr
collections:
  -
    label: "Settings"
    name: "settings"
    delete: false
    extension: "json"
    editor:
      preview: false
    files:
      -
        label: "Site Settings"
        name: "general"
        file: "site/_data/settings.json"
        fields:
          - {label: "Global site title", name: "site_title", widget: "string"}
          - {label: "Global site description", name: "site_description", widget: "string"}
          - {label: "Medium social url", name: "medium_url", widget: "string"}
          - {label: "Hackerone social url", name: "hackerone_url", widget: "string"}
          - {label: "Bugcrowd social url", name: "bugcrowd_url", widget: "string"}
  -
    label: "English site"
    name: "en_site"
    delete: false
    extension: "json"
    editor:
      preview: false
    files:
      -
        label: "Penrose page"
        name: "penrose"
        file: "site/_content/_en/penrose.json"
        fields:
          -
            label: "Navigation button text"
            name: "nav_content"
            widget: "string"
          -
            label: "Header settings"
            name: "header_content"
            widget: "object"
            fields:
              - {label: "Intro text", name: "intro", widget: "markdown"}
              - {label: "Button text", name: "btn", widget: "string"}
          -
            label: "Page settings"
            name: "page_content"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Content", name: "content", widget: "markdown"}
          -
            label: "Services"
            name: 'services'
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Icon", name: "icon", widget: "image"}
              - {label: "Subtitle", name: "subtitle", widget: "text", required: false}
              - {label: "Excerpt", name: "excerpt", widget: "text"}
              - {label: "Body", name: "body", widget: "markdown"}
      -
        label: "GDPR page"
        name: "gdpr"
        file: "site/_content/_en/gdpr.json"
        fields:
          -
            label: "Navigation button text"
            name: "nav_content"
            widget: "string"
          -
            label: "Page settings"
            name: "page_content"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
          -
            label: "Sections"
            name: 'sections'
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Icon", name: "icon", widget: "image"}
              - {label: "Subtitle", name: "subtitle", widget: "text", required: false}
              - {label: "Excerpt", name: "excerpt", widget: "text"}
          -
            label: "FAQS"
            name: 'faqs'
            widget: "list"
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "markdown"}
  -
    label: "Greek site"
    name: "gr_site"
    delete: false
    extension: "json"
    editor: 
      preview: false
    files:
      -
        label: "Penrose page"
        name: "penrose"
        file: "site/_content/_gr/penrose.json"
        fields:
          -
            label: "Navigation button text"
            name: "nav_content"
            widget: "string"
          -
            label: "Header settings"
            name: "header_content"
            widget: "object"
            fields:
              - {label: "Intro text", name: "intro", widget: "markdown"}
              - {label: "Button text", name: "btn", widget: "string"}
          -
            label: "Page settings"
            name: "page_content"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Content", name: "content", widget: "markdown"}
          -
            label: "Services"
            name: 'services'
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Icon", name: "icon", widget: "image"}
              - {label: "Subtitle", name: "subtitle", widget: "text", required: false}
              - {label: "Excerpt", name: "excerpt", widget: "text"}
              - {label: "Body", name: "body", widget: "markdown"}
      -
        label: "GDPR page"
        name: "gdpr"
        file: "site/_content/_gr/gdpr.json"
        fields:
          -
            label: "Navigation button text"
            name: "nav_content"
            widget: "string"
          -
            label: "Page settings"
            name: "page_content"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
          -
            label: "Sections"
            name: 'sections'
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Icon", name: "icon", widget: "image"}
              - {label: "Subtitle", name: "subtitle", widget: "text", required: false}
              - {label: "Excerpt", name: "excerpt", widget: "text"}
          -
            label: "FAQS"
            name: 'faqs'
            widget: "list"
            fields:
              - {label: "Question", name: "question", widget: "string"}
              - {label: "Answer", name: "answer", widget: "markdown"}
