backend:
  name  : github
  repo  : gaou-piou/Penrose
  branch: master
media_folder: "images/uploads"
collections:
  -
    label : "Settings"
    name  : "settings"
    delete: false
    extension: "json"
    editor: 
      preview: false
    files:
      -
        label : "Site Settings"
        name  : "general"
        file  : "site/_data/settings.json"
        fields: 
          - {label: "Global site title", name: "site_title", widget: "string"}
          - {label: "Global site description", name: "site_description", widget: "string"}
  -
    label: "Pages"
    name: "pages"
    delete: false
    extension: "json"
    editor: 
      preview: false
    files:
      -
        label: "Penrose page"
        name: "penrose"
        file: "site/content/penrose.json"
        fields:
          -
            label: "Navigation button text"
            name: "nav_content"
            widget: "object"
            fields:
              - {label: "English text", name: "en_text", widget: "string"}
              - {label: "Greek text", name: "gr_text", widget: "string"}
          -
            label: "Header settings"
            name: "header_content"
            widget: "object"
            fields:
              - {label: "English intro text", name: "en_intro", widget: "markdown"}
              - {label: "Greek intro text", name: "gr_intro", widget: "markdown"}
              - {label: "English button text", name: "en_btn", widget: "string"}
              - {label: "Greek button text", name: "gr_btn", widget: "string"}
          -
            label: "Page settings"
            name: "page_content"
            widget: "object"
            fields:
              - {label: "English title", name: "en_title", widget: "string"}
              - {label: "Greek title", name: "gr_title", widget: "string"}
              - {label: "English content", name: "en_content", widget: "markdown"}
              - {label: "Greek content", name: "gr_content", widget: "markdown"}

