backend:
  name  : github
  repo  : gaou-piou/Penrose
media_folder: "images/uploads"
collections:
  -
    label : "Settings"
    name  : "settings"
    delete: false
    extension: "json"
    editor: 
      preview: false
    files:
      -
        label : "Site Settings"
        name  : "general"
        file  : "site/_data/settings.json"
        fields:
          - {label: "Global site title", name: "site_title", widget: "string"}
          - {label: "Global site description", name: "site_description", widget: "string"}
          - {label: "Medium social url", name: "medium_url", widget: "string"}
          - {label: "Hackerone social url", name: "hackerone_url", widget: "string"}
          - {label: "Bugcrowd social url", name: "bugcrowd_url", widget: "string"}
